### PR TITLE
Add StringBuilder.AppendJoin

### PR DESCRIPTION
**Pull request by udaken**
There is no way to join the current ZString to avoid the allocation.
The BCL includes a StringBuilder.AppendJoin Method.
https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.appendjoin?view=netcore-3.1

I have implemented AppendJoin to ZString.

NOTE: This PR is waiting for #19 and #20.

### CODE REVIEW

**Comment by udaken** [comment]
The dependent PRs have been merged and the branch has been updated.

**Comment by udaken** [comment]
For testing, I couldn't find a class that implements `IList<T>` and doesn't implement `IReadOnlyList<T>` in BCL.

Therefore,  I apologize for not testing well against the `ReadOnlyListAdaptor<T>`.

**Comment by neuecc** [comment]
Thanks for the many contributes.
I checked this and #24, and ok to merge.
If merged it, I'll release new version so could you resolve conflict #21 and #24?

**Comment by udaken** [comment]
@neuecc Thanks for the review.
I fixed the conflict with #22.

**Pull request merged**
