### PR TITLE
Add ZStringWriter

### LINKED ISSUE #49: Built-in support for TextWriter implementations
Currently you cannot directly use `StringWriter` with ZString as `StringWriter` accepts regular `StringBuilder`. I created helper [ZStringWriter](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Abstractions/Pooling/ZStringWriter.cs) for Orchard Core. Would it make sense to offer `ZStringWriter` (UTF-16) and `Utf8ZStringWriter` out of the box?

If you think it's a viable option I could offer a PR, just tell me desired names for the classes and namespace.

### PR DESCRIPTION
**Pull request by lahma**
fixes #49

### CODE REVIEW

**Comment by lahma** [comment]
If `Utf8ValueStringBuilder` and `Utf16ValueStringBuilder` would implement an interface writer could also have a generic parameter. I think CLR would be able to inline it to direct struct usage without boxing.

**Comment by neuecc** [comment]
Sorry, I've focused to release new library [MessagePipe](https://github.com/Cysharp/MessagePipe/).
I've done most of it, so yes, I'll Merge the PR first, since it's unlikely to cause breaking changes in later expansions.

**Comment by neuecc** [comment]
Thank you!
I'll merge! (Any tweaks for Unity will be done by me after the merge and released soon after)

**Comment by sebastienros** [comment]
🤘

**Pull request merged**
